
var:
  env_dir: .e_ci
  python_version: "3.11"

jobs:
  _prepare:
    steps:
      - run: |
          if [ ! -d "${{ env_dir }}" ]; then
            python3 -m venv "${{ env_dir }}"
            . "${{ env_dir }}/bin/activate"
            pip install -r requirements.txt --disable-pip-version-check
            pip install -r requirements-linting.txt --disable-pip-version-check
            deactivate
          fi

  mypy:
    name: Runs mypy
    depends_on:
      - _prepare
    steps:
      - run: |
          . "${{ env_dir }}/bin/activate"
          mypy --version
          mypy --ignore-missing-imports --python-version=${{ python_version }} makesitex.py
          echo ""

  lint:
    name: Runs ruff
    depends_on:
      - _prepare
    steps:
      - run: |
          . "${{ env_dir }}/bin/activate"
          ruff version
          ruff check makesitex.py
          echo ""

  lint-fix:
    name: Reformats the code using ruff
    depends_on:
      - _prepare
    steps:
      - run: |
          . "${{ env_dir }}/bin/activate"
          ruff version
          ruff check --select I --fix makesitex.py
          ruff format makesitex.py
          echo ""
